#!C:\Users\chenyf29\Downloads\Eldercare_agent_ques\venv_310\Scripts\python.exe
# -*- coding: UTF-8 -*-
from __future__ import print_function, division, absolute_import

from numba.misc.numba_entry import main

if __name__ == "__main__":
    main()
